# Generated by Django 6.1.1 on 2026-09-26 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('SAFETY', 'Safety'), ('ENVIRONMENT', 'Environment'), ('PRODUCTION', 'Production'), ('LABOUR', 'Labour'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='mines.mine')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_compliances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
