# Generated by Django 6.1.1 on 2026-09-27 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0002_compliance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('ROUTINE', 'Routine Inspection'), ('SAFETY', 'Safety Inspection'), ('ENVIRONMENT', 'Environmental Inspection'), ('SURPRISE', 'Surprise Inspection'), ('COMPLIANCE', 'Compliance Inspection')], default='ROUTINE', max_length=30)),
                ('inspection_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('findings', models.TextField(blank=True, help_text='Inspection findings and observations')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(blank=True, limit_choices_to={'role': 'INSPECTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_conducted', to=settings.AUTH_USER_MODEL)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='mines.mine')),
            ],
        ),
    ]
