# Generated by Django 6.1.1 on 2026-09-27 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0004_violation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contractor_code', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('work_description', models.TextField(blank=True, help_text='Description of work performed by the contractor')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='mines.mine')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('LICENSE', 'License'), ('SAFETY_CERTIFICATE', 'Safety Certificate'), ('INSURANCE', 'Insurance'), ('LABOUR_LICENSE', 'Labour License'), ('ENVIRONMENTAL', 'Environmental Certificate'), ('OTHER', 'Other')], max_length=40)),
                ('document_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('issuing_authority', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('EXPIRING', 'Expiring Soon'), ('EXPIRED', 'Expired')], default='VALID', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mines.contractor')),
            ],
        ),
    ]
