# Generated by Django 6.1.1 on 2026-09-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='mine',
            name='risk_level',
            field=models.CharField(default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='mine',
            name='risk_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mine',
            name='risk_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
