# Generated by Django 6.1.1 on 2026-09-27 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0007_mine_risk_level_mine_risk_score_mine_risk_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_level', models.CharField(max_length=20)),
                ('risk_factors', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_history', to='mines.mine')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
